version: 0.2

phases:
  pre_build:
    commands:
      - cd client && npm install && cd ..
      - cd server && npm install
  build:
    commands:
      - cd client && npm run build
  post_build:
    commands:
      - mv ./packages/client/build ./client
      - mv ./packages/server ./server
artifacts:
  secondary-artifacts:
    client:
      files:
        - '**/*'
      base-directory: client
    server:
      files:
        - '**/*'
      base-directory: server
